import { Component, createSignal, createEffect, For, Show, onMount } from "solid-js";
import { invoke } from "@tauri-apps/api/core";
import "./ProviderSettings.css";

interface CustomProvider {
  id: string;
  name: string;
  base_url: string;
  api_key: string | null;
  model: string | null;
  temperature: number;
  max_tokens: number;
  timeout_secs: number;
}

interface ProviderPreset {
  name: string;
  base_url: string;
  requires_api_key: boolean;
  default_model: string | null;
  description: string;
}

interface ProviderSettingsProps {
  isOpen: boolean;
  onClose: () => void;
}

const ProviderSettings: Component<ProviderSettingsProps> = (props) => {
  const [providers, setProviders] = createSignal<CustomProvider[]>([]);
  const [presets, setPresets] = createSignal<ProviderPreset[]>([]);
  const [activeId, setActiveId] = createSignal<string | null>(null);
  const [editingProvider, setEditingProvider] = createSignal<CustomProvider | null>(null);
  const [isAddingNew, setIsAddingNew] = createSignal(false);
  const [selectedPreset, setSelectedPreset] = createSignal<string>("");
  const [testStatus, setTestStatus] = createSignal<Record<string, "idle" | "testing" | "success" | "error">>({});
  const [error, setError] = createSignal<string | null>(null);

  // Form state for editing/adding
  const [formData, setFormData] = createSignal<Partial<CustomProvider>>({
    name: "",
    base_url: "",
    api_key: null,
    model: null,
    temperature: 0.7,
    max_tokens: 4096,
    timeout_secs: 60,
  });

  const loadData = async () => {
    try {
      const [providerList, presetList, currentActiveId] = await Promise.all([
        invoke<CustomProvider[]>("custom_provider_list"),
        invoke<ProviderPreset[]>("custom_provider_get_presets"),
        invoke<string | null>("custom_provider_get_active_id"),
      ]);
      setProviders(providerList);
      setPresets(presetList);
      setActiveId(currentActiveId);
    } catch (e) {
      console.error("Failed to load provider data:", e);
      setError(`Failed to load providers: ${e}`);
    }
  };

  createEffect(() => {
    if (props.isOpen) {
      loadData();
      setError(null);
    }
  });

  const handlePresetSelect = (presetName: string) => {
    setSelectedPreset(presetName);
    const preset = presets().find((p) => p.name === presetName);
    if (preset) {
      setFormData({
        name: preset.name,
        base_url: preset.base_url,
        api_key: null,
        model: preset.default_model,
        temperature: 0.7,
        max_tokens: 4096,
        timeout_secs: 60,
      });
    }
  };

  const handleAddNew = () => {
    setIsAddingNew(true);
    setEditingProvider(null);
    setSelectedPreset("");
    setFormData({
      name: "",
      base_url: "",
      api_key: null,
      model: null,
      temperature: 0.7,
      max_tokens: 4096,
      timeout_secs: 60,
    });
  };

  const handleEdit = (provider: CustomProvider) => {
    setEditingProvider(provider);
    setIsAddingNew(false);
    setFormData({
      name: provider.name,
      base_url: provider.base_url,
      api_key: provider.api_key,
      model: provider.model,
      temperature: provider.temperature,
      max_tokens: provider.max_tokens,
      timeout_secs: provider.timeout_secs,
    });
  };

  const handleCancel = () => {
    setEditingProvider(null);
    setIsAddingNew(false);
    setError(null);
  };

  const handleSave = async () => {
    const data = formData();
    if (!data.name || !data.base_url) {
      setError("Name and URL are required");
      return;
    }

    try {
      if (isAddingNew()) {
        // Add new provider
        const newProvider: CustomProvider = {
          id: "", // Will be generated by backend
          name: data.name!,
          base_url: data.base_url!,
          api_key: data.api_key || null,
          model: data.model || null,
          temperature: data.temperature ?? 0.7,
          max_tokens: data.max_tokens ?? 4096,
          timeout_secs: data.timeout_secs ?? 60,
        };
        await invoke("custom_provider_add", { config: newProvider });
      } else if (editingProvider()) {
        // Update existing provider
        const updatedProvider: CustomProvider = {
          id: editingProvider()!.id,
          name: data.name!,
          base_url: data.base_url!,
          api_key: data.api_key || null,
          model: data.model || null,
          temperature: data.temperature ?? 0.7,
          max_tokens: data.max_tokens ?? 4096,
          timeout_secs: data.timeout_secs ?? 60,
        };
        await invoke("custom_provider_update", {
          id: editingProvider()!.id,
          config: updatedProvider,
        });
      }

      await loadData();
      handleCancel();
    } catch (e) {
      setError(`Failed to save provider: ${e}`);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this provider?")) return;

    try {
      await invoke("custom_provider_delete", { id });
      await loadData();
    } catch (e) {
      setError(`Failed to delete provider: ${e}`);
    }
  };

  const handleSetActive = async (id: string) => {
    try {
      await invoke("custom_provider_set_active", { id });
      setActiveId(id);
    } catch (e) {
      setError(`Failed to set active provider: ${e}`);
    }
  };

  const handleTest = async (id: string) => {
    setTestStatus((prev) => ({ ...prev, [id]: "testing" }));
    try {
      const success = await invoke<boolean>("custom_provider_test", { id });
      setTestStatus((prev) => ({ ...prev, [id]: success ? "success" : "error" }));

      // Reset status after 3 seconds
      setTimeout(() => {
        setTestStatus((prev) => ({ ...prev, [id]: "idle" }));
      }, 3000);
    } catch (e) {
      setTestStatus((prev) => ({ ...prev, [id]: "error" }));
      setTimeout(() => {
        setTestStatus((prev) => ({ ...prev, [id]: "idle" }));
      }, 3000);
    }
  };

  const getTestStatusIcon = (id: string): string => {
    const status = testStatus()[id] || "idle";
    switch (status) {
      case "testing":
        return "...";
      case "success":
        return "OK";
      case "error":
        return "Fail";
      default:
        return "Test";
    }
  };

  const getTestStatusClass = (id: string): string => {
    return testStatus()[id] || "idle";
  };

  return (
    <Show when={props.isOpen}>
      <div class="provider-settings-overlay" onClick={props.onClose}>
        <div class="provider-settings-modal" onClick={(e) => e.stopPropagation()}>
          <div class="modal-header">
            <h2>AI Services</h2>
            <button class="close-btn" onClick={props.onClose}>
              &times;
            </button>
          </div>

        <Show when={error()}>
          <div class="error-banner">
            {error()}
            <button onClick={() => setError(null)}>&times;</button>
          </div>
        </Show>

        <div class="modal-content">
          {/* Provider List */}
          <Show when={!isAddingNew() && !editingProvider()}>
            <div class="provider-list-section">
              <div class="section-header">
                <h3>Configured Services</h3>
                <button class="add-btn" onClick={handleAddNew}>
                  + Add Service
                </button>
              </div>

              <Show when={providers().length === 0}>
                <div class="empty-state">
                  <p>No services configured yet.</p>
                  <p>Click "Add Service" to get started.</p>
                </div>
              </Show>

              <div class="provider-cards">
                <For each={providers()}>
                  {(provider) => (
                    <div
                      class={`provider-card ${activeId() === provider.id ? "active" : ""}`}
                    >
                      <div class="card-header">
                        <div class="card-title">
                          <input
                            type="radio"
                            name="active-provider"
                            checked={activeId() === provider.id}
                            onChange={() => handleSetActive(provider.id)}
                          />
                          <span class="provider-name">{provider.name}</span>
                        </div>
                        <div class="card-actions">
                          <button
                            class={`test-btn ${getTestStatusClass(provider.id)}`}
                            onClick={() => handleTest(provider.id)}
                            disabled={testStatus()[provider.id] === "testing"}
                          >
                            {getTestStatusIcon(provider.id)}
                          </button>
                          <button class="edit-btn" onClick={() => handleEdit(provider)}>
                            Edit
                          </button>
                          <button
                            class="delete-btn"
                            onClick={() => handleDelete(provider.id)}
                          >
                            Delete
                          </button>
                        </div>
                      </div>
                      <div class="card-details">
                        <span class="detail-url">{provider.base_url}</span>
                        <Show when={provider.model}>
                          <span class="detail-model">Model: {provider.model}</span>
                        </Show>
                      </div>
                    </div>
                  )}
                </For>
              </div>
            </div>
          </Show>

          {/* Add/Edit Form */}
          <Show when={isAddingNew() || editingProvider()}>
            <div class="provider-form">
              <h3>{isAddingNew() ? "Add New Service" : "Edit Service"}</h3>

              <Show when={isAddingNew()}>
                <div class="form-group">
                  <label>Quick Start from Preset</label>
                  <select
                    value={selectedPreset()}
                    onChange={(e) => handlePresetSelect(e.currentTarget.value)}
                  >
                    <option value="">-- Select a preset --</option>
                    <For each={presets()}>
                      {(preset) => (
                        <option value={preset.name}>{preset.name} - {preset.description}</option>
                      )}
                    </For>
                  </select>
                </div>

                <div class="form-divider">Or configure manually</div>
              </Show>

              <div class="form-group">
                <label>Service Name *</label>
                <input
                  type="text"
                  value={formData().name || ""}
                  onInput={(e) =>
                    setFormData((prev) => ({ ...prev, name: e.currentTarget.value }))
                  }
                  placeholder="e.g., My OpenAI"
                />
              </div>

              <div class="form-group">
                <label>API Base URL *</label>
                <input
                  type="text"
                  value={formData().base_url || ""}
                  onInput={(e) =>
                    setFormData((prev) => ({ ...prev, base_url: e.currentTarget.value }))
                  }
                  placeholder="e.g., https://api.openai.com/v1"
                />
              </div>

              <div class="form-group">
                <label>API Key</label>
                <input
                  type="password"
                  value={formData().api_key || ""}
                  onInput={(e) =>
                    setFormData((prev) => ({
                      ...prev,
                      api_key: e.currentTarget.value || null,
                    }))
                  }
                  placeholder="sk-..."
                />
              </div>

              <div class="form-group">
                <label>Model</label>
                <input
                  type="text"
                  value={formData().model || ""}
                  onInput={(e) =>
                    setFormData((prev) => ({
                      ...prev,
                      model: e.currentTarget.value || null,
                    }))
                  }
                  placeholder="e.g., gpt-4, llama3.2 (optional)"
                />
              </div>

              <div class="form-row">
                <div class="form-group">
                  <label>Temperature</label>
                  <input
                    type="number"
                    min="0"
                    max="2"
                    step="0.1"
                    value={formData().temperature ?? 0.7}
                    onInput={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        temperature: parseFloat(e.currentTarget.value) || 0.7,
                      }))
                    }
                  />
                </div>

                <div class="form-group">
                  <label>Max Tokens</label>
                  <input
                    type="number"
                    min="100"
                    max="128000"
                    step="100"
                    value={formData().max_tokens ?? 4096}
                    onInput={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        max_tokens: parseInt(e.currentTarget.value) || 4096,
                      }))
                    }
                  />
                </div>

                <div class="form-group">
                  <label>Timeout (s)</label>
                  <input
                    type="number"
                    min="10"
                    max="600"
                    value={formData().timeout_secs ?? 60}
                    onInput={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        timeout_secs: parseInt(e.currentTarget.value) || 60,
                      }))
                    }
                  />
                </div>
              </div>

              <div class="form-actions">
                <button class="cancel-btn" onClick={handleCancel}>
                  Cancel
                </button>
                <button class="save-btn" onClick={handleSave}>
                  {isAddingNew() ? "Add Service" : "Save Changes"}
                </button>
              </div>
            </div>
          </Show>
        </div>
      </div>
    </div>
    </Show>
  );
};

export default ProviderSettings;
